export const ROUTE_STOPS = [
    { name: "Σύνταγμα", en_name: "Syntagma Square", pct: 0, coords: "37.9755,23.7348", desc: "Η καρδιά της Αθήνας.", en_desc: "The heart of Athens.", videoSrc: "KDv7gtpSEuI" },
    { name: "Μουσείο Μπενάκη", en_name: "Benaki Museum", pct: 10, coords: "37.9760,23.7406", desc: "Ένα από τα σημαντικότερα μουσεία.", en_desc: "Important museum.", videoSrc: "wKJWPAnFVyw" },
    { name: "Καλλιμάρμαρο", en_name: "Panathenaic Stadium", pct: 20, coords: "37.9685,23.7411", desc: "Παναθηναϊκό Στάδιο.", en_desc: "First modern Olympics.", videoSrc: "KLByRyNO4bo" },
    { name: "Πύλη Αδριανού", en_name: "Hadrian's Arch", pct: 30, coords: "37.9693,23.7320", desc: "Ρωμαϊκό μνημείο.", en_desc: "Roman monument.", videoSrc: "X8eW6EWlY-0" },
    { name: "Ακρόπολη", en_name: "Acropolis", pct: 40, coords: "37.9715,23.7257", desc: "Ο Παρθενώνας.", en_desc: "The Parthenon.", videoSrc: "35POa0UMr4A" },
    { name: "Θησείο", en_name: "Thiseio", pct: 50, coords: "37.9764,23.7214", desc: "Περαντζάδα και καφέ.", en_desc: "Cafes and promenade.", videoSrc: "iqXdwnSZNQU" },
    { name: "Μοναστηράκι", en_name: "Monastiraki", pct: 60, coords: "37.9760,23.7256", desc: "Η παλιά αγορά.", en_desc: "Flea market.", videoSrc: "9DpH31wutu8" },
    { name: "Ομόνοια", en_name: "Omonoia", pct: 70, coords: "37.9841,23.7281", desc: "Ιστορικό εμπορικό κέντρο.", en_desc: "Commercial center.", videoSrc: "tX-N_UpJdbQ" },
    { name: "Ακαδημία", en_name: "Academy", pct: 80, coords: "37.9803,23.7336", desc: "Η τριλογία της Αθήνας.", en_desc: "Neoclassical Trilogy.", videoSrc: "KDv7gtpSEuI" },
    { name: "Σύνταγμα (Τέρμα)", en_name: "Syntagma (Term)", pct: 100, coords: "37.9755,23.7348", desc: "Επιστροφή.", en_desc: "Return.", videoSrc: "KDv7gtpSEuI" }
];

export const OPT_COFFEE = ["Σκέτος", "Μέτριος", "Γλυκός", "Με Γάλα"];

export const CONFIG = {
    baseSpeed: 0.15,
    zoneDurations: { 'left': 15, 'right': 15, 'aisle': 10 },
    shops: [
        { id: 1, name: "Coffee Route", cat: "Καφές", en_cat: "Coffee", deliverTo: 10, color: "bg-amber-100 text-amber-600", img: "fa-mug-hot", products: [{ n: "Espresso", p: 2.0 }, { n: "Freddo Espresso", p: 3.5, opt: OPT_COFFEE }, { n: "Freddo Cappuccino", p: 3.8, opt: OPT_COFFEE }, { n: "Cappuccino", p: 3.5, opt: OPT_COFFEE }, { n: "Latte", p: 4.0 }, { n: "Ελληνικός", p: 2.0, opt: OPT_COFFEE }] },
        { id: 2, name: "Attic Bakery", cat: "Street Food", en_cat: "Street Food", deliverTo: 20, color: "bg-orange-100 text-orange-600", img: "fa-bread-slice", products: [{ n: "Τυρόπιτα", p: 2.2 }, { n: "Κρουασάν Βουτύρου", p: 2.0 }, { n: "Κρουασάν Σοκολάτας", p: 2.5 }, { n: "Σπανακόπιτα", p: 2.4 }, { n: "Μπουγάτσα", p: 2.8 }, { n: "Σάντουιτς Γαλοπούλα", p: 4.5 }] },
        { id: 3, name: "Juice & Green", cat: "Street Food", en_cat: "Healthy", deliverTo: 30, color: "bg-lime-100 text-lime-600", img: "fa-carrot", products: [{ n: "Χυμός Πορτοκάλι", p: 3.5 }, { n: "Χυμός Ανάμεικτος", p: 4.5 }, { n: "Smoothie Energy", p: 5.0 }, { n: "Σαλάτα Καίσαρα", p: 6.5 }, { n: "Φρουτοσαλάτα", p: 4.0 }, { n: "Μπάρα Δημητριακών", p: 2.0 }] },
        { id: 4, name: "Souvlaki GR", cat: "Street Food", en_cat: "Street Food", deliverTo: 40, color: "bg-blue-100 text-blue-600", img: "fa-utensils", products: [{ n: "Πίτα Γύρο Χοιρινό", p: 3.8 }, { n: "Πίτα Γύρο Κοτόπουλο", p: 3.8 }, { n: "Πίτα Καλαμάκι", p: 3.5 }, { n: "Μερίδα Γύρος", p: 8.5 }, { n: "Χωριάτικη Σαλάτα", p: 6.0 }, { n: "Πατάτες", p: 3.0 }] },
        { id: 5, name: "Sweet Home", cat: "Γλυκά", en_cat: "Sweets", deliverTo: 50, color: "bg-pink-100 text-pink-600", img: "fa-ice-cream", products: [{ n: "Βάφλα Σοκολάτα", p: 5.0 }, { n: "Παγωτό (Μπάλα)", p: 2.5 }, { n: "Σουφλέ Σοκολάτας", p: 4.5 }, { n: "Cheesecake", p: 4.0 }, { n: "Milkshake", p: 4.5 }, { n: "Κρέπα", p: 4.5 }] },
        { id: 6, name: "Pizza Fanatics", cat: "Street Food", en_cat: "Street Food", deliverTo: 60, color: "bg-red-100 text-red-600", img: "fa-pizza-slice", products: [{ n: "Pizza Special (8κομ)", p: 12.0 }, { n: "Pizza Margarita", p: 9.0 }, { n: "Slice Special", p: 3.0 }, { n: "Calzone", p: 5.0 }, { n: "Peinirli", p: 4.0 }, { n: "Coca Cola", p: 1.5 }] },
        { id: 7, name: "Sushi Stop", cat: "Street Food", en_cat: "Street Food", deliverTo: 70, color: "bg-slate-200 text-slate-600", img: "fa-fish", products: [{ n: "Sushi Combo (12pcs)", p: 15.0 }, { n: "Salmon Roll (6pcs)", p: 6.0 }, { n: "California Roll", p: 6.0 }, { n: "Nigiri Salmon", p: 5.0 }, { n: "Edamame", p: 3.5 }] },
        { id: 8, name: "Everest", cat: "Καφές", en_cat: "Coffee", deliverTo: 80, color: "bg-red-50 text-red-600", img: "fa-mountain", products: [{ n: "Freddo Espresso", p: 3.2 }, { n: "Sandwich Chef", p: 4.8 }, { n: "Donut Choco", p: 1.8 }, { n: "Orange Juice", p: 3.5 }, { n: "Water 500ml", p: 0.5 }] },
        { id: 9, name: "Grigoris", cat: "Καφές", en_cat: "Coffee", deliverTo: 90, color: "bg-green-50 text-green-700", img: "fa-mug-hot", products: [{ n: "Freddo Cappuccino", p: 3.2 }, { n: "Spanakopita", p: 2.4 }, { n: "Kourapies", p: 1.0 }, { n: "Hot Dog", p: 2.5 }, { n: "Fresh Juice", p: 3.0 }] }
    ]
};

export const DICT = {
    "GUEST": { gr: "ΕΠΙΣΚΕΠΤΗΣ", en: "GUEST" },
    "PASSENGER": { gr: "ΕΠΙΒΑΤΗΣ", en: "PASSENGER" },
    "DRIVER MODE": { gr: "ΟΔΗΓΟΣ", en: "DRIVER MODE" },
    "Delivery": { gr: "Delivery", en: "Delivery" },
    "Θέα & Πλοήγηση": { gr: "Θέα & Πλοήγηση", en: "Tour & View" },
    "Gemini Assistant": { gr: "Gemini Assistant", en: "AI Assistant" },
    "Κλιματισμός": { gr: "Κλιματισμός", en: "A/C Control" },
    "Συστήματα & HVAC": { gr: "Συστήματα & HVAC", en: "Bus Systems" },
    "Καθαρισμός": { gr: "Καθαρισμός", en: "Cleaning Bot" },
    "Όλα": { gr: "Όλα", en: "All" },
    "Καφές": { gr: "Καφές", en: "Coffee" },
    "Φαγητό": { gr: "Φαγητό", en: "Food" },
    "Γλυκά": { gr: "Γλυκά", en: "Sweets" },
    "Καλάθι": { gr: "Καλάθι", en: "Your Cart" },
    "Σύνολο": { gr: "Σύνολο", en: "Total" },
    "Ολοκλήρωση": { gr: "Ολοκλήρωση", en: "Checkout" },
    "Το καλάθι είναι άδειο": { gr: "Το καλάθι είναι άδειο", en: "Cart is empty" },
    "ΕΠΟΜΕΝΗ ΣΤΑΣΗ": { gr: "ΕΠΟΜΕΝΗ ΣΤΑΣΗ", en: "NEXT STOP" },
    "Ανάγνωση": { gr: "Ανάγνωση", en: "Read Aloud" },
    "Διαδραστικός Χάρτης": { gr: "Διαδραστικός Χάρτης", en: "Live Map" },
    "Θέα Οδηγού": { gr: "Θέα Οδηγού", en: "Dashcam" },
    "Live Dashcam": { gr: "Ζωντανή Πορεία", en: "Live Route" },
    "Ενεργοποίηση AR": { gr: "Ενεργοποίηση AR Κάμερας", en: "Turn On AR Camera" },
    "Κάμερα Ανενεργή": { gr: "Κάμερα Ανενεργή", en: "Camera Offline" },
    "Σφάλμα κάμερας. Ελέγξτε τις άδειες.": { gr: "Σφάλμα κάμερας. Ελέγξτε τις άδειες.", en: "Camera error. Check permissions." },
    "Κάμερα ενεργοποιήθηκε": { gr: "Η κάμερα ενεργοποιήθηκε", en: "Camera activated" },
    "Επιλογή Θέσης": { gr: "Επιλογή Θέσης", en: "Select your Seat" },
    "Επιλέξτε πού κάθεστε": { gr: "Επιλέξτε πού κάθεστε", en: "Select your seat on the bus" },
    "Επιβεβαίωση": { gr: "Επιβεβαίωση", en: "Confirm" },
    "AR Σάρωση": { gr: "Ανάλυση Εικόνας", en: "Analyze Image" },
    "Ανάλυση μέσω AI...": { gr: "Το AI αναλύει την εικόνα...", en: "AI is analyzing image..." },
    "Κλείσιμο AR": { gr: "Επιστροφή στην Κάμερα", en: "Back to Camera" },
    "Δεν βρέθηκε αξιοθέατο": { gr: "Δεν αναγνωρίστηκε αξιοθέατο", en: "No landmark detected" },
    "Παρακαλώ δείξτε ένα γνωστό αξιοθέατο.": { gr: "Παρακαλώ δείξτε κάποιο αξιοθέατο ή κτίριο.", en: "Please point at a known building or landmark." },
    "Πίνακας Ελέγχου": { gr: "Πίνακας Ελέγχου", en: "Control Panel" },
    "Χειροκίνητο Άδειασμα": { gr: "Χειροκίνητο Άδειασμα", en: "Manual Empty" },
    "Sim: Εύρεση Αντικειμένου": { gr: "Sim: Εύρεση Αντικειμένου", en: "Sim: Find Object" },
    "Κάτοψη Λεωφορείου": { gr: "Κάτοψη Λεωφορείου", en: "Bus Layout" },
    "Αριστερά": { gr: "Αριστερά (15s)", en: "Left (15s)" },
    "Διάδρομος": { gr: "ΔΙΑΔΡΟΜΟΣ (10s)", en: "AISLE (10s)" },
    "Δεξιά": { gr: "Δεξιά (15s)", en: "Right (15s)" },
    "Κατάσταση": { gr: "Κατάσταση", en: "Status" },
    "Χρόνος": { gr: "Χρόνος", en: "Time" },
    "Κάδος": { gr: "Κάδος", en: "Bin" },
    "Μπαταρία": { gr: "Μπαταρία", en: "Battery" },
    "Αναμονή": { gr: "💤 Αναμονή", en: "💤 Standby" },
    "Καθαρίζει": { gr: "⚡ Καθαρισμός...", en: "⚡ Cleaning..." },
    "Παίξε & Κέρδισε Έκπτωση!": { gr: "Παίξε & Κέρδισε Έκπτωση!", en: "Play & Win Discount!" },
    "Έκπτωση -10%": { gr: "Έκπτωση -10%", en: "Discount -10%" },
    "UNAVAILABLE": { gr: "ΜΗ ΔΙΑΘΕΣΙΜΟ", en: "UNAVAILABLE" },
    "OPEN": { gr: "● ΑΝΟΙΧΤΟ", en: "● OPEN" },
    "TAKING_ORDERS": { gr: "ΔΕΧΕΤΑΙ ΠΑΡΑΓΓΕΛΙΕΣ", en: "TAKING ORDERS" },
    "Κέντρο Ελέγχου Λεωφορείου": { gr: "Κέντρο Ελέγχου", en: "Control Center" },
    "Βοηθός Οδήγησης": { gr: "Βοηθός Οδήγησης", en: "Drive Assist" },
    "Όριο Ταχύτητας": { gr: "Όριο Ταχύτητας", en: "Speed Limit" },
    "Έξυπνος Κλιματισμός": { gr: "Έξυπνος Κλιματισμός", en: "Smart HVAC" },
    "Κατάσταση Οδηγού: Κανονική": { gr: "Κατάσταση Οδηγού: Κανονική", en: "Driver State: Normal" },
    "ΣΥΣΤΗΜΑ ON/OFF": { gr: "ΣΥΣΤΗΜΑ ON/OFF", en: "SYSTEM ON/OFF" },
    "Ενέργεια & Οροφή": { gr: "Ενέργεια & Οροφή", en: "Energy & Roof" },
    "Καταναλωση Τωρα": { gr: "Καταναλωση Τωρα", en: "Current Usage" },
    "Παραγωγη PV": { gr: "Παραγωγη PV", en: "PV Production" },
    "ΑΝΟΙΓΜΑ ΟΡΟΦΗΣ": { gr: "ΑΝΟΙΓΜΑ ΟΡΟΦΗΣ", en: "OPEN ROOF" },
    "ΚΛΕΙΣΙΜΟ ΟΡΟΦΗΣ": { gr: "ΚΛΕΙΣΙΜΟ ΟΡΟΦΗΣ", en: "CLOSE ROOF" },
    "Πληρωμή με Κάρτα": { gr: "Πληρωμή με Κάρτα", en: "Card Payment" },
    "Αριθμος Καρτας": { gr: "Αριθμός Κάρτας", en: "Card Number" },
    "HΜ. ΛΗΞΗΣ": { gr: "ΗΜ. ΛΗΞΗΣ", en: "EXP. DATE" },
    "CVC": { gr: "CVC", en: "CVC" },
    "Ακύρωση": { gr: "Ακύρωση", en: "Cancel" },
    "Επιλογή Στάσης Παραλαβής": { gr: "Επιλογή Στάσης Παραλαβής", en: "Select Pickup Stop" },
    "Προσθήκη στο Καλάθι": { gr: "Προσθήκη στο Καλάθι", en: "Add to Cart" },
    "Επιλογές": { gr: "Επιλογές", en: "Options" },
    "SYS_START": { gr: "Το σύστημα τηλεμετρίας ενεργοποιήθηκε.", en: "Telemetry system initialized." },
    "AC_SYS_ON": { gr: "Κεντρικό σύστημα HVAC: ON", en: "Master HVAC System: ON" },
    "AC_SYS_OFF": { gr: "Κεντρικό σύστημα HVAC: OFF", en: "Master HVAC System: OFF" },
    "ROOF_OPEN": { gr: "Η ηλιακή οροφή άνοιξε.", en: "Solar roof OPENED." },
    "ROOF_CLOSE": { gr: "Η ηλιακή οροφή έκλεισε.", en: "Solar roof CLOSED." },
    "MANUAL_STOP": { gr: "ΕΚΤΑΚΤΗ ΑΝΑΓΚΗ: Ο κινητήρας έσβησε.", en: "EMERGENCY: Engine stopped." },
    "MANUAL_START": { gr: "Ο κινητήρας επανεκκινήθηκε.", en: "Engine restarted successfully." },
    "BOT_START": { gr: "Ρομπότ Καθαρισμού: Ξεκίνησε περιπολία.", en: "Cleaning Bot: Patrol started." },
    "BOT_FULL": { gr: "Ρομπότ: Σφάλμα - Ο κάδος είναι γεμάτος.", en: "Bot Error: Bin is full." },
    "BOT_EMPTY": { gr: "Ρομπότ: Ο κάδος άδειασε επιτυχώς.", en: "Bot: Bin emptied successfully." },
    "BOT_DONE": { gr: "Ρομπότ: Ολοκλήρωση καθαρισμού.", en: "Bot: Task completed." },
    "ITEM_FOUND": { gr: "Αναφορά: Το ρομπότ βρήκε χαμένο αντικείμενο.", en: "Report: Cleaning bot found a lost item." },
    "FATIGUE_WARN": { gr: "ΣΥΝΑΓΕΡΜΟΣ ΑΣΦΑΛΕΙΑΣ: Εντοπίστηκε κόπωση οδηγού.", en: "SAFETY ALERT: Driver fatigue detected." }
};